// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATCjzkF8PyHLk31aK6qMlh6ch_hgWbuFk',
    appId: '1:831654821280:web:73665a6a99da20f552f8c5',
    messagingSenderId: '831654821280',
    projectId: 'keep-notes-clone-3454e',
    authDomain: 'keep-notes-clone-3454e.firebaseapp.com',
    storageBucket: 'keep-notes-clone-3454e.appspot.com',
    measurementId: 'G-NYYZEZE74W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwORVNJDbAwngXTi1yVrgYu5PhpOyS7Jc',
    appId: '1:831654821280:android:442d264f21dec8c452f8c5',
    messagingSenderId: '831654821280',
    projectId: 'keep-notes-clone-3454e',
    storageBucket: 'keep-notes-clone-3454e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1vDIwMaCFMwPnNqr6bS9OW4WIA99nKM0',
    appId: '1:831654821280:ios:17e3c08d4329dc1252f8c5',
    messagingSenderId: '831654821280',
    projectId: 'keep-notes-clone-3454e',
    storageBucket: 'keep-notes-clone-3454e.appspot.com',
    iosClientId: '831654821280-usnliq522ikiq6q5l7hgc41qmodldhju.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleKeepNotesClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1vDIwMaCFMwPnNqr6bS9OW4WIA99nKM0',
    appId: '1:831654821280:ios:17e3c08d4329dc1252f8c5',
    messagingSenderId: '831654821280',
    projectId: 'keep-notes-clone-3454e',
    storageBucket: 'keep-notes-clone-3454e.appspot.com',
    iosClientId: '831654821280-usnliq522ikiq6q5l7hgc41qmodldhju.apps.googleusercontent.com',
    iosBundleId: 'com.example.googleKeepNotesClone',
  );
}
